name: NodeJS AuthAPI Action

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Environment
      run : cp /home/abjs/githubDeploy/Auth/.env ./     
    - name: Node Install     
      run : npm i
    - name: PM2 Resatart
      run : pm2 restart AuthAPI
